# Generated by Django 5.0.2 on 2024-03-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_customuser_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_img_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
