# Generated by Django 5.0.2 on 2024-03-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_order_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to="files/"),
        ),
    ]
