# Generated by Django 5.0.2 on 2024-03-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="street",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="zip",
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="date",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="zip",
            field=models.CharField(max_length=10),
        ),
    ]
