# Generated by Django 5.0.2 on 2024-04-01 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_customuser_city_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(default="review", max_length=50),
        ),
        migrations.AlterField(
            model_name="file",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="base.order",
            ),
        ),
    ]
