# Generated by Django 5.0.2 on 2024-04-02 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_order_status_alter_file_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='review', max_length=40),
        ),
    ]
