# Generated by Django 5.0.2 on 2024-04-18 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_message_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
    ]
