# Generated by Django 5.0.2 on 2024-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_file_message_alter_file_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_numer', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
