# Generated by Django 5.0.2 on 2024-05-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='phone_numer',
            new_name='phone_number',
        ),
    ]
