# Generated by Django 5.0.2 on 2024-08-04 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_order_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime',
            new_name='timestamp',
        ),
    ]
