# Generated by Django 5.0.2 on 2024-08-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_rename_datetime_order_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
