# Generated by Django 5.0.2 on 2025-10-31 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_order_new'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestObject',
        ),
    ]
