# Generated by Django 5.0.2 on 2025-11-08 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_request_requestobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_review_id', models.CharField(max_length=255, unique=True)),
                ('place_id', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('profile_photo_url', models.URLField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField()),
                ('original_language', models.CharField(max_length=10)),
                ('original_text', models.TextField()),
                ('review_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-review_timestamp'],
            },
        ),
    ]
