# Generated by Django 5.0.2 on 2025-11-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=10)),
                ('translated_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='base.review')),
            ],
            options={
                'unique_together': {('review', 'language')},
            },
        ),
    ]
