# Generated by Django 5.0.2 on 2025-11-09 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_emailverification_code_alter_customuser_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='email',
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
