# Generated by Django 5.0.2 on 2025-12-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_emailverification_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('ready_pick_up', 'Pick Up Ready'), ('sent', 'Sent'), ('canceled', 'Canceled')], default='review', max_length=40),
        ),
    ]
