# Generated by Django 5.2.9 on 2025-12-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_chat_requestanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestanswer',
            name='answer_text',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
