# Generated by Django 5.2.9 on 2025-12-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_requestanswer_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('costs_estimate', 'Costs Estimate'), ('order', 'Order')], default='order', max_length=40),
        ),
    ]
