# Generated by Django 5.2.9 on 2025-12-21 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_translation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='new',
            new_name='is_new',
        ),
    ]
