# Generated by Django 5.2.9 on 2025-12-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_rename_new_order_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestobject',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
