# Generated by Django 5.0.2 on 2026-01-26 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_requestobject_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ManyToManyField(blank=True, null=True, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
