# Generated by Django 5.0.2 on 2026-02-10 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_remove_message_receiver_message_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('rechnung', 'Invoice'), ('stripe', 'Stripe')], max_length=40, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('ua', 'Ua'), ('ru', 'Ru'), ('de', 'De')], default='ua', max_length=40)),
                ('type', models.CharField(choices=[('Geburtsurkunde', 'Geburtsurkunde'), ('Heiratsurkunde', 'Heiratsurkunde'), ('Sterbeurkunde', 'Sterbeurkunde'), ('Scheidungsurkunde', 'Scheidungsurkunde'), ('Sonstige', 'Sonstige')], default='Sonstige', max_length=40)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.order')),
            ],
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
