# Generated by Django 5.0.2 on 2026-02-10 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_order_paid_order_payment_type_document_delete_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='individual_price',
            field=models.BooleanField(default=False),
        ),
    ]
