# Generated by Django 5.0.2 on 2026-02-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_document_individual_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='Sonstiges Dokument', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('kostenvoranschlag', 'Costs Estimate'), ('order', 'Order')], default='order', max_length=40),
        ),
    ]
