# Generated by Django 5.0.2 on 2026-02-12 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_alter_document_type_alter_order_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='paid',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('paid', 'Paid'), ('not_paid', 'Not Paid'), ('payment_pending', 'Payment Pending'), ('payment_canceled', 'Payment Canceled')], default='not_paid', max_length=40),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('ready_pick_up', 'Pick Up Ready'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('waiting_for_payment', 'Waiting For Payment')], default='review', max_length=40),
        ),
    ]
