# Generated by Django 5.0.2 on 2026-02-13 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_remove_order_paid_order_payment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cost_estimates/')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_estimate', to='base.order')),
            ],
        ),
    ]
