# Generated by Django 5.0.2 on 2026-02-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_costestimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='Sonstiges Dokument', max_length=255),
        ),
    ]
