# Generated by Django 5.0.2 on 2026-02-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_alter_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lexoffice_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
