# Generated by Django 5.0.2 on 2026-02-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_add_lexoffice_id_to_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
