# Generated by Django 5.0.2 on 2026-02-15 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
