# Generated by Django 5.0.2 on 2026-03-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_phone_number_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('pick_up', 'Pick Up'), ('post', 'Post')], default='pick_up', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='express',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('review', 'Review'), ('in_progress', 'In Progress'), ('ready_pick_up', 'Pick Up Ready'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('waiting_for_payment', 'Waiting For Payment')], default='review', max_length=40),
        ),
    ]
